baseURL = 'https://betsyze.github.io/betsy-hugo/'
languageCode = 'en-us'
title = 'Coyote Spider Buffalo'
theme = "shibui"

[params]
  author = "Betsyze"
  email = "betsy.z.ellison@gmail.com"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2